"""
Extract the glass-insulator subset from the official InsPLAD raw directory
using filename lists under annotation/.

Place downloaded and extracted InsPLAD at: datasets/raw/InsPLAD/
By default, all images under raw/InsPLAD/ are indexed recursively (any subdirectory
can match filenames in the manifests).
To narrow scope, pass --glass-subdir to index only that subdirectory (e.g. glass_insulator).

Prepare merged LabelMe bundles under annotation/ beforehand (not generated by this script):
  - train_mask.json
  - test_missingcap.json

Default one-shot pipeline: copy images from raw -> generate binary masks from the JSON above
-> rename each directory to 000.*, ... (use --no-* to skip a step).

Output directory: datasets/InsPLAD/glass-insulator/
  - train/good/          <- annotation/train_good.txt
  - test/good/           <- annotation/test_good.txt
  - test/missingcap/     <- annotation/test_missingcap.txt

Manifest files list one filename per line; blank lines and lines starting with # are ignored.
"""

from __future__ import annotations

import argparse
import json
import shutil
import sys
from pathlib import Path

from labelme_mask_utils import (
    BUNDLE_FORMAT,
    TEST_MISSINGCAP_JSON,
    TRAIN_MASK_JSON,
    load_merged_bundle,
    mask_out_path_from_image_path,
    rasterize_labelme_item,
    save_mask_png,
)

IMAGE_SUFFIXES = {".png", ".bmp", ".jpeg", ".jpg", ".tif", ".tiff", ".webp"}
IMAGE_SUFFIXES |= {s.upper() for s in IMAGE_SUFFIXES}

REN_IMAGE_EXTS = {
    ".png",
    ".bmp",
    ".jpeg",
    ".jpg",
    ".tif",
    ".tiff",
    ".webp",
    ".PNG",
    ".JPEG",
    ".JPG",
    ".BMP",
}


def _project_root() -> Path:
    return Path(__file__).resolve().parent.parent


def _resolve_raw_search_root(raw_root: Path, glass_subdir: str) -> Path:
    """
    Resolve the directory used to build the filename index.
    When glass_subdir is empty or ".", search for images recursively under raw_root.
    """
    base = raw_root.resolve()
    s = (glass_subdir or "").strip().replace("\\", "/").strip("/")
    if not s or s == ".":
        return base
    return (base / s).resolve()


def _iter_manifest_lines(path: Path) -> list[str]:
    text = path.read_text(encoding="utf-8")
    lines = []
    for line in text.splitlines():
        s = line.strip()
        if not s or s.startswith("#"):
            continue
        lines.append(s)
    return lines


def _build_basename_index(search_root: Path) -> dict[str, Path]:
    """basename(lower) -> first path found; warns on duplicate basenames."""
    index: dict[str, Path] = {}
    dup: list[tuple[str, Path, Path]] = []
    for p in search_root.rglob("*"):
        if not p.is_file():
            continue
        if p.suffix not in IMAGE_SUFFIXES:
            continue
        key = p.name.lower()
        if key in index:
            dup.append((key, index[key], p))
        else:
            index[key] = p
    if dup:
        for key, a, b in dup[:10]:
            print(f"[WARN] duplicate basename '{key}': keeping {a}, ignoring {b}", file=sys.stderr)
        if len(dup) > 10:
            print(f"[WARN] ... and {len(dup) - 10} more duplicate basenames", file=sys.stderr)
    return index


def _resolve_source(name: str, index: dict[str, Path]) -> Path | None:
    key = name.lower()
    if key in index:
        return index[key]
    stem = Path(name).stem.lower()
    for k, p in index.items():
        if Path(k).stem.lower() == stem:
            return p
    return None


def _clean_image_dir(d: Path, dry_run: bool) -> None:
    if not d.is_dir():
        return
    for p in d.iterdir():
        if p.is_file() and p.suffix in IMAGE_SUFFIXES:
            if dry_run:
                print(f"[DRY] delete {p}")
            else:
                p.unlink()


def _clean_mask_dir(d: Path, dry_run: bool) -> None:
    if not d.is_dir():
        return
    for p in d.iterdir():
        if p.is_file() and p.suffix.lower() == ".png":
            if dry_run:
                print(f"[DRY] delete {p}")
            else:
                p.unlink()


def run_masks_from_merged(out_root: Path, dry_run: bool, clean_masks: bool) -> tuple[int, int]:
    ann = out_root / "annotation"
    train_json = ann / TRAIN_MASK_JSON
    test_json = ann / TEST_MISSINGCAP_JSON
    mask_train = out_root / "mask"
    mask_test = out_root / "ground_truth" / "missingcap"

    if not train_json.is_file() or not test_json.is_file():
        print(
            "[ERROR] Missing merged annotation files (prepare format=insplad_labelme_bundle JSON yourself):\n"
            f"  {train_json}\n"
            f"  {test_json}",
            file=sys.stderr,
        )
        sys.exit(1)

    if clean_masks:
        _clean_mask_dir(mask_train, dry_run)
        _clean_mask_dir(mask_test, dry_run)

    ok, skipped = 0, 0
    for merged_path, dest_dir in [
        (train_json, mask_train),
        (test_json, mask_test),
    ]:
        bundle = load_merged_bundle(merged_path)
        items = bundle.get("items", [])
        print(f"[INFO] Masks from {merged_path.name}: {len(items)} items -> {dest_dir}")
        for item in items:
            try:
                mask, image_path = rasterize_labelme_item(item)
            except Exception as e:
                print(f"[ERROR] {merged_path.name} imagePath={item.get('imagePath')!r}: {e}", file=sys.stderr)
                skipped += 1
                continue
            out_name = mask_out_path_from_image_path(image_path)
            dst = dest_dir / out_name
            if dry_run:
                print(f"[DRY] mask -> {dst}")
            else:
                save_mask_png(mask, dst)
            ok += 1
    print(f"[DONE] masks written={ok}, errors={skipped}")
    return ok, skipped


def run_copy_images(args) -> tuple[int, int]:
    """Returns (total_ok, total_miss)."""
    raw_search = _resolve_raw_search_root(args.raw_root, args.glass_subdir)
    if not raw_search.is_dir():
        print(f"[ERROR] Source directory not found: {raw_search}", file=sys.stderr)
        sys.exit(1)

    ann = (args.out / "annotation").resolve()
    specs = [
        (ann / "train_good.txt", args.out / "train" / "good"),
        (ann / "test_good.txt", args.out / "test" / "good"),
        (ann / "test_missingcap.txt", args.out / "test" / "missingcap"),
    ]

    for manifest, _ in specs:
        if not manifest.is_file():
            print(f"[ERROR] Manifest missing: {manifest}", file=sys.stderr)
            sys.exit(1)

    print(f"[INFO] Indexing images under {raw_search} ...")
    index = _build_basename_index(raw_search)
    print(f"[INFO] Found {len(index)} image files.")

    if args.clean:
        for _, dest in specs:
            _clean_image_dir(dest, args.dry_run)

    total_ok = 0
    total_miss = 0

    for manifest, dest_dir in specs:
        names = _iter_manifest_lines(manifest)
        print(f"[INFO] {manifest.name}: {len(names)} entries -> {dest_dir}")
        if not args.dry_run:
            dest_dir.mkdir(parents=True, exist_ok=True)

        for name in names:
            src = _resolve_source(name, index)
            if src is None:
                print(f"[MISS] {name}", file=sys.stderr)
                total_miss += 1
                continue
            dst = dest_dir / name
            if args.dry_run:
                print(f"[DRY] {src} -> {dst}")
            else:
                shutil.copy2(src, dst)
            total_ok += 1

    print(f"[DONE] copied={total_ok}, missing={total_miss}")
    return total_ok, total_miss


def _renumber_pad_width(n: int) -> int:
    if n <= 0:
        return 3
    return max(3, len(str(n - 1)))


def _renumber_sorted_image_paths(d: Path, exts: set[str]) -> list[Path]:
    files = [p for p in d.iterdir() if p.is_file() and p.suffix in exts]
    files.sort(key=lambda p: p.stem.lower())
    return files


def _renumber_sorted_new_names(mapping: dict[str, str]) -> list[str]:
    if not mapping:
        return []
    return sorted(mapping.values(), key=lambda n: int(Path(n).stem))


def _renumber_two_phase_rename(pairs: list[tuple[Path, str]], dry_run: bool) -> None:
    if dry_run:
        for p, new_name in pairs:
            print(f"[DRY] {p.name} -> {new_name}")
        return
    tmps: list[tuple[Path, str]] = []
    for i, (p, new_name) in enumerate(pairs):
        tmp = p.with_name(f".__renseq_{i:05d}{p.suffix}")
        p.rename(tmp)
        tmps.append((tmp, new_name))
    for tmp, new_name in tmps:
        final = tmp.parent / new_name
        tmp.rename(final)


def run_sequential_renumber(out_root: Path, dry_run: bool) -> None:
    """
    Renumber each directory independently from 000; train images and masks, and test
    defect images and ground_truth, share the same index when paired by stem.
    Extensions are normalized to lowercase .jpg / .png / .json.
    """
    train_good = out_root / "train" / "good"
    test_good = out_root / "test" / "good"
    test_mc = out_root / "test" / "missingcap"
    mask_dir = out_root / "mask"
    gt_mc = out_root / "ground_truth" / "missingcap"
    ann = out_root / "annotation"
    ann_train_json_dir = ann / "train_mask"
    ann_test_json_dir = ann / "test_missingcap"

    def renumber_simple(dir_path: Path, kind: str) -> dict[str, str]:
        if not dir_path.is_dir():
            print(f"[SKIP] {kind}: directory missing {dir_path}", file=sys.stderr)
            return {}
        paths = _renumber_sorted_image_paths(dir_path, REN_IMAGE_EXTS)
        if not paths:
            print(f"[SKIP] {kind}: no files in {dir_path}", file=sys.stderr)
            return {}
        w = _renumber_pad_width(len(paths))
        mapping: dict[str, str] = {}
        pairs: list[tuple[Path, str]] = []
        for i, p in enumerate(paths):
            new_name = f"{i:0{w}d}{p.suffix.lower()}"
            mapping[p.name] = new_name
            pairs.append((p, new_name))
        print(f"[INFO] Renumber {kind}: {len(pairs)} files in {dir_path}")
        _renumber_two_phase_rename(pairs, dry_run)
        return mapping

    def renumber_paired_images_masks(
        img_dir: Path,
        mask_d: Path,
        label_img: str,
    ) -> tuple[dict[str, str], dict[str, str]]:
        img_map: dict[str, str] = {}
        mask_map: dict[str, str] = {}
        if not img_dir.is_dir() or not mask_d.is_dir():
            print(f"[SKIP] paired {label_img}: missing dir", file=sys.stderr)
            return img_map, mask_map
        imgs = _renumber_sorted_image_paths(img_dir, REN_IMAGE_EXTS)
        masks = sorted(
            [p for p in mask_d.iterdir() if p.is_file() and p.suffix.lower() == ".png"],
            key=lambda p: p.stem.lower(),
        )
        n = min(len(imgs), len(masks))
        if len(imgs) != len(masks):
            print(
                f"[WARN] {label_img}: image count {len(imgs)} != mask count {len(masks)}; pairing first {n}",
                file=sys.stderr,
            )
        if n == 0:
            return img_map, mask_map
        w = _renumber_pad_width(n)
        pairs: list[tuple[Path, str]] = []
        for i in range(n):
            img, m = imgs[i], masks[i]
            if img.stem.lower() != m.stem.lower():
                print(
                    f"[WARN] {label_img}: stem mismatch {img.name} vs {m.name} at index {i}",
                    file=sys.stderr,
                )
            new_img = f"{i:0{w}d}{img.suffix.lower()}"
            new_mask = f"{i:0{w}d}.png"
            img_map[img.name] = new_img
            mask_map[m.name] = new_mask
            pairs.append((img, new_img))
            pairs.append((m, new_mask))
        print(f"[INFO] Renumber paired {label_img}: {n} image+mask pairs")
        _renumber_two_phase_rename(pairs, dry_run)
        return img_map, mask_map

    def renumber_labelme_json_dir(
        json_dir: Path,
        img_mapping: dict[str, str],
        label: str,
    ) -> None:
        if not json_dir.is_dir() or not img_mapping:
            return
        json_paths = sorted(
            [p for p in json_dir.iterdir() if p.is_file() and p.suffix.lower() == ".json"],
            key=lambda p: p.stem.lower(),
        )
        json_paths = [p for p in json_paths if p.name not in (TRAIN_MASK_JSON, TEST_MISSINGCAP_JSON)]

        old_img_names_sorted = sorted(img_mapping.keys(), key=lambda n: Path(n).stem.lower())

        if len(json_paths) != len(old_img_names_sorted):
            print(
                f"[WARN] {label}: json count {len(json_paths)} != image mapping {len(old_img_names_sorted)}",
                file=sys.stderr,
            )
        n = min(len(json_paths), len(old_img_names_sorted))
        if n == 0:
            return
        wj = _renumber_pad_width(n)
        pairs: list[tuple[Path, str]] = []
        for i in range(n):
            jp = json_paths[i]
            old_img = old_img_names_sorted[i]
            if Path(old_img).stem.lower() != jp.stem.lower():
                print(
                    f"[WARN] {label}: order mismatch at {i}: json {jp.name} vs image {old_img}",
                    file=sys.stderr,
                )
            new_img_bn = img_mapping.get(old_img)
            if not new_img_bn:
                continue
            data = json.loads(jp.read_text(encoding="utf-8"))
            data["imagePath"] = new_img_bn
            new_json = f"{i:0{wj}d}.json"
            if not dry_run:
                jp.write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding="utf-8")
            pairs.append((jp, new_json))
        print(f"[INFO] Renumber {label}: {len(pairs)} json files")
        _renumber_two_phase_rename(pairs, dry_run)

    img_map_train, _ = renumber_paired_images_masks(train_good, mask_dir, "train+mask")
    map_test_good = renumber_simple(test_good, "test/good")
    img_map_mc, _ = renumber_paired_images_masks(test_mc, gt_mc, "test_missingcap+gt")

    if img_map_train:
        renumber_labelme_json_dir(ann_train_json_dir, img_map_train, "annotation/train_mask")
    if img_map_mc:
        renumber_labelme_json_dir(ann_test_json_dir, img_map_mc, "annotation/test_missingcap")

    def update_merged(path: Path, img_mapping: dict[str, str]) -> None:
        if not path.is_file() or not img_mapping:
            return
        bundle = json.loads(path.read_text(encoding="utf-8"))
        if bundle.get("format") != BUNDLE_FORMAT:
            print(f"[WARN] {path} unexpected format", file=sys.stderr)
        changed = 0
        for item in bundle.get("items", []):
            ip = item.get("imagePath")
            if not ip:
                continue
            bn = Path(ip).name
            if bn in img_mapping:
                item["imagePath"] = img_mapping[bn]
                changed += 1
        if dry_run:
            print(f"[DRY] update {path}: would rewrite {changed} imagePath entries")
        else:
            path.write_text(json.dumps(bundle, ensure_ascii=False, indent=2), encoding="utf-8")
            print(f"[INFO] Updated {path} ({changed} imagePath)")

    update_merged(ann / TRAIN_MASK_JSON, img_map_train)
    update_merged(ann / TEST_MISSINGCAP_JSON, img_map_mc)

    def write_manifest(rel_name: str, mapping: dict[str, str], dir_path: Path) -> None:
        mpath = ann / rel_name
        if not mapping:
            return
        lines = _renumber_sorted_new_names(mapping)
        if dry_run:
            print(f"[DRY] rewrite {mpath} ({len(lines)} lines)")
            return
        if not dir_path.is_dir():
            return
        mpath.write_text("\n".join(lines) + "\n", encoding="utf-8")
        print(f"[INFO] Wrote {mpath}")

    write_manifest("train_good.txt", img_map_train, train_good)
    write_manifest("test_good.txt", map_test_good, test_good)
    write_manifest("test_missingcap.txt", img_map_mc, test_mc)

    print("[DONE] sequential renumber finished")


def main() -> None:
    root = _project_root()
    default_raw = root / "datasets" / "raw" / "InsPLAD"
    default_out = root / "datasets" / "InsPLAD" / "glass-insulator"

    parser = argparse.ArgumentParser(
        description="Build InsPLAD glass-insulator subset: copy images, masks from merged JSON, renumber (all on by default).",
    )
    parser.add_argument(
        "--raw-root",
        type=Path,
        default=default_raw,
        help=f"Path to unpacked InsPLAD root (default: {default_raw})",
    )
    parser.add_argument(
        "--glass-subdir",
        type=str,
        default="",
        help="Optional: only index images under raw-root/<this> (recursive). "
        "Default empty = index entire raw-root tree.",
    )
    parser.add_argument(
        "--out",
        type=Path,
        default=default_out,
        help=f"Output glass-insulator root (default: {default_out})",
    )
    parser.add_argument(
        "--clean",
        action="store_true",
        help="Remove existing image files in train/good, test/good, test/missingcap before copying",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print planned actions without writing files",
    )
    parser.add_argument(
        "--no-images",
        action="store_true",
        help="Skip copying train/test images from raw InsPLAD",
    )
    parser.add_argument(
        "--no-masks",
        action="store_true",
        help="Skip generating mask/ and ground_truth/missingcap/ PNGs",
    )
    parser.add_argument(
        "--clean-masks",
        action="store_true",
        help="Before writing masks, remove existing PNG files in mask/ and ground_truth/missingcap/",
    )
    parser.add_argument(
        "--no-renumber",
        action="store_true",
        help="Skip renaming files to 000.*, 001.* and updating manifests/JSON",
    )
    args = parser.parse_args()

    exit_code = 0
    out = args.out.resolve()

    if not args.no_images:
        _, total_miss = run_copy_images(args)
        if total_miss:
            exit_code = 2

    if not args.no_masks:
        _, m_err = run_masks_from_merged(out, args.dry_run, args.clean_masks)
        if m_err:
            exit_code = max(exit_code, 3)

    if not args.no_renumber:
        run_sequential_renumber(out, args.dry_run)

    if exit_code:
        sys.exit(exit_code)


if __name__ == "__main__":
    main()
